inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard/cop/semantic_blocks
  - rubocop-inclusivity

inherit_gem:
  standard:
    - config/base.yml

Inclusivity:
  Enabled: true

Naming/FileName:
  Exclude:
    - lib/rubocop-inclusivity.rb
