Inclusivity/Race:
  Description: "Avoid racially charged language."
  Enabled: true
  Offenses:
    whitelist:
      - allowlist
      - passlist
      - permitlist
    blacklist:
      - banlist
      - blocklist
      - denylist
    slave:
      - secondary
