Inclusivity/Race:
  Description: >-
    Suggests replacing racially-charged or insensitive language with more
    accurate and inclusive words.
  Reference: https://github.com/rails/rails/issues/33677
  Enabled: true
  Offenses:
    whitelist:
      - allowlist
      - passlist
      - permitlist
    blacklist:
      - banlist
      - blocklist
      - denylist
    slave:
      - secondary
