name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Run RSpec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
